const container = document.querySelector('#container');


const p = document.createElement('p');
p.textContent = "This is the second paragraph. This content does not exist in the HTML document, it is generated by the script. It appears on the DOM, but it is not added to the HTML document.";
p.style.color = 'blue';
container.appendChild(p);

const div = document.createElement('div');
div.style.backgroundColor = 'pink';
div.style.border = '2px solid black';

const h2 = document.createElement('h2');
h2.textContent = "A subtitle created by the script";

const p_div = document.createElement('p');
p_div.textContent = 'A paragraph inside a div. This content and the subtitle are generated by the script.';

div.appendChild(h2);
div.appendChild(p_div);
container.appendChild(div);